# 학교 좌표별 계산 다시

In [2]:
# 학교 
import pandas as pd 

schol1 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','유치원', engine='openpyxl')
schol2 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','초등학교', engine='openpyxl')
schol3 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','중학교', engine='openpyxl')
schol4 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','고등학교', engine='openpyxl')
schol5 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','대학교', engine='openpyxl')
schol6 = pd.read_excel('/data1/KSW/아산시/교수님꺼/data/(학교)아산전체학교_정제(완).xlsx','대학원', engine='openpyxl')

In [11]:
from tqdm import tqdm
schol1['좌표']=''
for i in tqdm(range(len(schol1))):
    schol1['좌표'][i] = (schol1['위도'][i],schol1['경도'][i])

  0%|          | 0/60 [00:00<?, ?it/s]/tmp/ipykernel_19565/761965862.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol1['좌표'][i] = (schol1['위도'][i],schol1['경도'][i])
100%|██████████| 60/60 [00:00<00:00, 127.04it/s]

In [ ]:
schol1['좌표']=''
for i in tqdm(range(len(schol1))):
    schol1['좌표'][i] = (schol1['위도'][i],schol1['경도'][i])
    
schol2['좌표']=''
for i in tqdm(range(len(schol2))):
    schol2['좌표'][i] = (schol2['위도'][i],schol2['경도'][i])
    
schol3['좌표']=''
for i in tqdm(range(len(schol3))):
    schol3['좌표'][i] = (schol3['위도'][i],schol3['경도'][i])
    
schol4['좌표']=''
for i in tqdm(range(len(schol4))):
    schol4['좌표'][i] = (schol4['위도'][i],schol4['경도'][i])

schol5['좌표']=''
for i in tqdm(range(len(schol5))):
    schol5['좌표'][i] = (schol5['Latitude'][i],schol5['Longitude'][i])
    
schol6['좌표']=''
for i in tqdm(range(len(schol6))):
    schol6['좌표'][i] = (schol6['Latitude'][i],schol6['Longitude'][i])

In [12]:
schol2['좌표']=''
for i in tqdm(range(len(schol2))):
    schol2['좌표'][i] = (schol2['위도'][i],schol2['경도'][i])

  0%|          | 0/46 [00:00<?, ?it/s]/tmp/ipykernel_19565/1614673039.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol2['좌표'][i] = (schol2['위도'][i],schol2['경도'][i])
100%|██████████| 46/46 [00:00<00:00, 172.31it/s]

In [13]:
schol3['좌표']=''
for i in tqdm(range(len(schol3))):
    schol3['좌표'][i] = (schol3['위도'][i],schol3['경도'][i])

  0%|          | 0/19 [00:00<?, ?it/s]/tmp/ipykernel_19565/997598222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol3['좌표'][i] = (schol3['위도'][i],schol3['경도'][i])
100%|██████████| 19/19 [00:00<00:00, 136.17it/s]

In [14]:
schol4['좌표']=''
for i in tqdm(range(len(schol4))):
    schol4['좌표'][i] = (schol4['위도'][i],schol4['경도'][i])

  0%|          | 0/30 [00:00<?, ?it/s]/tmp/ipykernel_19565/2218842811.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol4['좌표'][i] = (schol4['위도'][i],schol4['경도'][i])
100%|██████████| 30/30 [00:00<00:00, 157.58it/s]

In [17]:
schol5['좌표']=''
for i in tqdm(range(len(schol5))):
    schol5['좌표'][i] = (schol5['Latitude'][i],schol5['Longitude'][i])

  0%|          | 0/15 [00:00<?, ?it/s]/tmp/ipykernel_19565/2012029652.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol5['좌표'][i] = (schol5['Latitude'][i],schol5['Longitude'][i])
100%|██████████| 15/15 [00:00<00:00, 135.19it/s]

In [18]:
schol6['좌표']=''
for i in tqdm(range(len(schol6))):
    schol6['좌표'][i] = (schol6['Latitude'][i],schol6['Longitude'][i])

  0%|          | 0/69 [00:00<?, ?it/s]/tmp/ipykernel_19565/2810174655.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  schol6['좌표'][i] = (schol6['Latitude'][i],schol6['Longitude'][i])
100%|██████████| 69/69 [00:00<00:00, 197.23it/s]

In [19]:
schol6

,Unnamed: 0,대학교명,대학원명,읍면동,도로명주소,측정년도,학교수,학과수(석사),학과수(박사),입학정원수(석사),...,박사과정,석사과정(지원자),석사과정(입학자),박사과정(지원자),박사과정(입학자),Latitude,Longitude,행정동중심_위도,행정동중심_경도,좌표
0,0,선문대학교,일반대학원,탕정면,선문로221번길 70,2019,1,23,21,58,...,21,57,47,65,50,36.798350,127.073155,36.809157,127.068452,"(36.79835, 127.0731546)"
1,1,선문대학교,신학전문대학원,탕정면,선문로221번길 70,2019,0,0,0,0,...,1,0,0,0,0,36.798350,127.073155,36.809157,127.068452,"(36.79835, 127.0731546)"
2,2,선문대학교,교육대학원,탕정면,선문로221번길 70,2019,1,2,0,20,...,0,15,11,0,0,36.798350,127.073155,36.809157,127.068452,"(36.79835, 127.0731546)"
3,3,선문대학교,글로컬통합대학원,탕정면,선문로221번길 70,2019,1,6,0,139,...,0,52,40,0,0,36.798350,127.073155,36.809157,127.068452,"(36.79835, 127.0731546)"
4,4,선문대학교,신학대학원,탕정면,선문로221번길 70,2019,1,2,0,15,...,0,8,5,0,0,36.798350,127.073155,36.809157,127.068452,"(36.79835, 127.0731546)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,64,순천향대학교,행정대학원,신창면,순천향로 22,2021,0,0,0,0,...,0,0,0,0,0,36.769649,126.932408,36.790769,126.933819,"(36.7696489, 126.9324079)"
65,65,순천향대학교,글로벌경영대학원,신창면,순천향로 22,2021,0,0,0,0,...,0,0,0,0,0,36.769649,126.932408,36.790769,126.933819,"(36.7696489, 126.9324079)"
66,66,호서대학교,일반대학원,배방읍,호서로 79번길,2021,1,45,34,134,...,42,89,78,51,50,36.737340,127.076545,36.754095,127.068357,"(36.7373397, 127.0765454)"
67,67,호서대학교,기술경영전문대학원,배방읍,호서로 79번길,2021,1,2,1,26,...,9,37,26,31,21,36.737340,127.076545,36.754095,127.068357,"(36.7373397, 127.0765454)"
68,68,호서대학교,스포츠과학대학원,배방읍,호서로 79번길,2021,1,7,0,23,...,0,15,10,0,0,36.737340,127.076545,36.754095,127.068357,"(36.7373397, 127.0765454)"

In [20]:
proposed_site=pd.read_excel('./data/결과주소(layer5+건물x)_결과(행정동).xlsx', engine='openpyxl')

In [22]:
need_proposed_site = proposed_site[['Unnamed: 0','위도','경도','A11','A12','A14','A16','A18','A20','행정동','_PARCEL_AD']]
need_proposed_site.columns=['index','위도','경도','지목명','토지면적','용도지역명1','용도지역명2','토지이용상황','지형높이','행정동','지번주소']

In [28]:
# 후보지 데이터에 좌표 칼럼 추가
need_proposed_site['좌표']=''
for i in range(len(need_proposed_site)):
    need_proposed_site['좌표'][i] = (need_proposed_site['위도'][i],need_proposed_site['경도'][i])

/tmp/ipykernel_19565/3277249195.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['좌표']=''
/tmp/ipykernel_19565/3277249195.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['좌표'][i] = (need_proposed_site['위도'][i],need_proposed_site['경도'][i])

In [29]:
need_proposed_site

,index,위도,경도,지목명,토지면적,용도지역명1,용도지역명2,토지이용상황,지형높이,행정동,지번주소,좌표
0,0,36.782392,127.005628,대,1070.1,일반상업지역,지정되지않음,상업나지,평지,온양1동,충청남도 아산시 온천동 85-1,"(36.78239195, 127.0056275)"
1,1,36.777425,127.005741,과수원,1491.0,제2종일반주거지역,지정되지않음,주거나지,평지,온양2동,충청남도 아산시 온천동 130-54,"(36.77742498, 127.0057406)"
2,2,36.792304,126.999302,대,1363.0,제2종일반주거지역,지정되지않음,주거나지,평지,온양1동,충청남도 아산시 온천동 1087,"(36.79230426, 126.9993017)"
3,3,36.793572,126.999076,주차장,975.0,자연녹지지역,지정되지않음,주거기타,평지,온양1동,충청남도 아산시 온천동 1098,"(36.79357194, 126.9990764)"
4,4,36.785831,126.999372,대,1064.8,일반상업지역,지정되지않음,주거나지,평지,온양1동,충청남도 아산시 온천동 1338,"(36.78583083, 126.9993721)"
...,...,...,...,...,...,...,...,...,...,...,...,...
2268,2268,36.812654,126.903331,과수원,3807.0,계획관리지역,지정되지않음,과수원,평지,신창면,충청남도 아산시 신창면 신곡리 48-5,"(36.81265381, 126.903331)"
2269,2269,36.812766,126.897723,임야,3362.0,계획관리지역,지정되지않음,과수원,완경사,신창면,충청남도 아산시 신창면 신곡리 산 82,"(36.81276628, 126.8977233)"
2270,2270,36.798774,126.899822,대,998.0,계획관리지역,지정되지않음,주거나지,평지,신창면,충청남도 아산시 신창면 가내리 118,"(36.79877381, 126.8998221)"
2271,2271,36.804541,126.886628,과수원,2940.0,계획관리지역,농림지역,과수원,평지,신창면,충청남도 아산시 신창면 가내리 613-8,"(36.80454108, 126.8866282)"
2272,2272,36.804774,126.887043,임야,953.0,계획관리지역,지정되지않음,토지임야,평지,신창면,충청남도 아산시 신창면 가내리 산 60-2,"(36.8047741, 126.8870428)"

In [ ]:
need_proposed_site['반경내 문화시설수'] = 0
for i in tqdm(range(len(need_proposed_site))):
    for j in range(len(shop)):
        if haversine(need_proposed_site['좌표'][i],shop['좌표'][j], unit = 'm')  <= 600 :
             need_proposed_site['반경내 문화시설수'][i] += 1

In [ ]:
# 시간오래걸려서 따로 빼서 ㄱ

In [25]:
# 전처리된 유동인구데이터에 위경도전환한 데이터 
trans21_lg=pd.read_pickle('/data1/SHJ/좌표_튜플.pkl')

In [30]:
# trans21_t의 coord_x, coord_y 를 위경도로 변환하여 trans21_lg로 불러옴
trans21_lg.columns = ['T1','T2','T3','T4','T5','T6','T7','좌표']
trans21_lg

# 유동인구 요인변수 2개  
trans21_lg['유소년ㆍ청년ㆍ노년 유동인구'] = trans21_lg['T1']+ trans21_lg['T2'] + trans21_lg['T3'] + trans21_lg['T6']
trans21_lg['중장년 유동인구'] = trans21_lg['T4']+ trans21_lg['T5']

유동인구= trans21_lg[['유소년ㆍ청년ㆍ노년 유동인구','중장년 유동인구','좌표']]
유동인구 # 행정동별 주민등록인구 수 요인변수

         유소년ㆍ청년ㆍ노년 유동인구  중장년 유동인구                                        좌표
0                  6.71      4.34   (36.78560969907209, 127.02686183503569)
1                 19.16      7.97   (36.78741258830925, 127.02685075043442)
2                174.31    112.12  (36.787863310532515, 127.02684797913008)
3                 31.10     18.40    (36.78831403272137, 127.0268452077641)
4               1709.45   1144.65   (36.78921547699581, 127.02683966484727)
...                 ...       ...                                       ...
1058697            0.21      0.32  (36.791466856428706, 127.02626540351343)
1058698           23.52     12.09     (36.782003918946, 127.02688400128098)
1058699           16.90     12.48  (36.782454641582206, 127.02688123071593)
1058700           17.58     11.18     (36.782905364184, 127.02687846008928)
1058701           13.76      7.98  (36.783356086751375, 127.02687568940102)

[1058702 rows x 3 columns]

In [32]:
from haversine import haversine

# 위경도 입력
Seoul = (37.541, 126.986)  #Latitude, Longitude
Toronto = (43.65, -79.38)

# 거리 계산
haversine(Seoul, Toronto, unit = 'm')

10603855.192138562

In [ ]:
need_proposed_site['유소년ㆍ청년ㆍ노년 유동인구수'] = 0
need_proposed_site['중장년 유동인구수'] = 0
for i in tqdm(range(len(need_proposed_site))):
    for j in range(len(유동인구)):
        if haversine(need_proposed_site['좌표'][i],유동인구['좌표'][j], unit = 'm')  <= 500 : # 500m반경내
            need_proposed_site['유소년ㆍ청년ㆍ노년 유동인구수'][i] += 유동인구['유소년ㆍ청년ㆍ노년 유동인구'][j]
            need_proposed_site['중장년 유동인구수'][i] += 유동인구['중장년 유동인구'][j]

/tmp/ipykernel_19565/897948053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['유소년ㆍ청년ㆍ노년 유동인구수'] = 0
/tmp/ipykernel_19565/897948053.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['중장년 유동인구수'] = 0
  0%|          | 0/2273 [00:00<?, ?it/s]/tmp/ipykernel_19565/897948053.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['유소년ㆍ청년ㆍ노년 유동인구수'][i] += 유동인구['유소년ㆍ청년ㆍ노년 유동인구'][j]
/tmp/ipykernel_19565/897948053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_proposed_site['중장년 유동인구수'][i] += 유동인구['중장년 유동인구'][j]
 36%|███▋      | 827/2273 [6:35:34<16:25:51, 40.91s/it]

In [34]:
need_proposed_site

,index,위도,경도,지목명,토지면적,용도지역명1,용도지역명2,토지이용상황,지형높이,행정동,지번주소,좌표,유동인구수,유소년ㆍ청년ㆍ노년 유동인구수,중장년 유동인구수
0,0,36.782392,127.005628,대,1070.1,일반상업지역,지정되지않음,상업나지,평지,온양1동,충청남도 아산시 온천동 85-1,"(36.78239195, 127.0056275)",0,22933237.08,12099574.16
1,1,36.777425,127.005741,과수원,1491.0,제2종일반주거지역,지정되지않음,주거나지,평지,온양2동,충청남도 아산시 온천동 130-54,"(36.77742498, 127.0057406)",0,14549669.24,7214699.04
2,2,36.792304,126.999302,대,1363.0,제2종일반주거지역,지정되지않음,주거나지,평지,온양1동,충청남도 아산시 온천동 1087,"(36.79230426, 126.9993017)",0,4149524.58,2620256.79
3,3,36.793572,126.999076,주차장,975.0,자연녹지지역,지정되지않음,주거기타,평지,온양1동,충청남도 아산시 온천동 1098,"(36.79357194, 126.9990764)",0,2310350.62,1448825.00
4,4,36.785831,126.999372,대,1064.8,일반상업지역,지정되지않음,주거나지,평지,온양1동,충청남도 아산시 온천동 1338,"(36.78583083, 126.9993721)",0,9962053.03,6222103.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2268,2268,36.812654,126.903331,과수원,3807.0,계획관리지역,지정되지않음,과수원,평지,신창면,충청남도 아산시 신창면 신곡리 48-5,"(36.81265381, 126.903331)",0,248804.45,213817.64
2269,2269,36.812766,126.897723,임야,3362.0,계획관리지역,지정되지않음,과수원,완경사,신창면,충청남도 아산시 신창면 신곡리 산 82,"(36.81276628, 126.8977233)",0,253426.40,212203.59
2270,2270,36.798774,126.899822,대,998.0,계획관리지역,지정되지않음,주거나지,평지,신창면,충청남도 아산시 신창면 가내리 118,"(36.79877381, 126.8998221)",0,146582.04,112932.38
2271,2271,36.804541,126.886628,과수원,2940.0,계획관리지역,농림지역,과수원,평지,신창면,충청남도 아산시 신창면 가내리 613-8,"(36.80454108, 126.8866282)",0,182109.96,141908.78
2272,2272,36.804774,126.887043,임야,953.0,계획관리지역,지정되지않음,토지임야,평지,신창면,충청남도 아산시 신창면 가내리 산 60-2,"(36.8047741, 126.8870428)",0,182232.46,142003.79